Repository Bjorgeh/rapportsystem-frontend, pull requests merged in 2024-03, with the labels that each got.

#33 Login response data
  src/contexts/auth-context.js
  src/pages/auth/newsubuser.js
Labels: enhancement

#34 Worksesh result
  src/layouts/dashboard/config.js
  src/pages/index.js
  src/sections/overview/overview-sales.js
Labels: enhancement

#37 import API URL
  src/config/apiConnection.js
  src/contexts/auth-context.js
  src/pages/auth/newsubuser.js
  src/pages/index.js
Labels: enhancement

#38 lagt til adminpanel
  src/contexts/auth-context.js
  src/layouts/dashboard/config.js
  src/layouts/dashboard/side-nav.js
  src/pages/admin/adminpanel.js
  src/pages/admin/func/changesubpass.js
  src/pages/admin/func/deletesubuser.js
  src/pages/admin/func/newsubuser.js
  src/pages/auth/login.js
Labels: enhancement

#39 updated auth-context
  src/contexts/auth-context.js
Labels: bug

#40 settings page
  src/layouts/dashboard/config.js
  src/layouts/dashboard/side-nav.js
  src/pages/admin/adminpanel.js
  src/pages/index.js
  src/pages/settings.js
  src/sections/settings/settings-activity.js
  src/sections/settings/settings-password.js
Labels: enhancement

#41 User info panel
  src/contexts/auth-context.js
  src/pages/account.js
  src/sections/account/account-profile-details.js
  src/sections/account/account-profile.js
Labels: enhancement

#42 bug with login responsdata
  src/contexts/auth-context.js
  src/pages/account.js
  src/sections/account/account-profile-details.js
Labels: bug

#43 ryddet top-nav
  src/layouts/dashboard/account-popover.js
  src/layouts/dashboard/top-nav.js
Labels: enhancement

#45 updated side-nav
  src/layouts/dashboard/side-nav.js
Labels: Small fix

#48 lagt til valg for diagram index.js
  src/layouts/dashboard/config.js
  src/pages/index.js
  src/pages/reports.js
Labels: enhancement
