Repository Bjorgeh/rapportsystem-frontend, pull requests merged in 2024-04, with the labels that each got.

#49 Get values from API for frontpage graph
  .eslintrc.json
  .gitattributes
  .gitignore
  .npmrc
  README.md
  next.config.js
  package-lock.json
  package.json
  src/guards/auth-guard.js
  src/pages/index.js
  src/sections/overview/overview-sales.js
Labels: enhancement

#50 Added buttons to overview page
  package.json
  src/pages/index.js
  src/pages/settings.js
Labels: enhancement

#51 Leader panel
  src/layouts/dashboard/config.js
  src/layouts/dashboard/side-nav.js
  src/pages/leader/leaderpanel.js
Labels: enhancement

#54 update index.js
  src/pages/index.js
Labels: bug

#62 57 Oversett "Sync" og "Overview" knappene på forsiden
  src/pages/index.js
  src/sections/overview/overview-sales.js
Labels: enhancement

#61 #56 Removed 'K' suffix for chart values
  src/sections/overview/overview-sales.js
Labels: bug

#65 47 Final clean-up of files and code
  .editorconfig
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  README.md
  jsconfig.json
  next.config.js
  package.json
  public/manifest.json
  src/components/severity-pill.js
  src/contexts/auth-context.js
  src/hooks/use-mocked-user.js
  src/hooks/use-selection.js
  src/layouts/dashboard/side-nav.js
  src/pages/_document.js
  src/pages/admin/adminpanel.js
  src/pages/admin/func/changesubpass.js
  src/pages/admin/func/deletesubuser.js
  src/pages/admin/func/newsubuser.js
  src/pages/auth/login.js
  src/pages/dynamicRead.js
  src/pages/index.js
  src/pages/leader/leaderpanel.js
  src/pages/reports.js
  src/sections/account/account-profile-details.js
  src/sections/account/account-profile.js
  src/sections/overview/overview-sales.js
  src/sections/settings/settings-activity.js
  src/utils/apply-pagination.js
  src/utils/create-resource-id.js
  src/utils/get-initials.js
Labels: cleanup

#66 Comment cleanup
  src/contexts/auth-context.js
  src/guards/auth-guard.js
  src/layouts/auth/layout.js
  src/layouts/dashboard/account-popover.js
  src/layouts/dashboard/config.js
  src/layouts/dashboard/side-nav-item.js
  src/layouts/dashboard/side-nav.js
  src/layouts/dashboard/top-nav.js
  src/pages/admin/adminpanel.js
  src/pages/admin/func/changesubpass.js
  src/pages/admin/func/deletesubuser.js
  src/pages/admin/func/newsubuser.js
  src/pages/auth/login.js
  src/pages/index.js
  src/pages/readBorreproveRapport.js
  src/pages/readDisaRapport.js
  src/pages/readSandanalyseRapport.js
  src/pages/readSkrapRapport.js
  src/pages/readSmelteRapport.js
  src/pages/reports.js
  src/sections/account/account-profile-details.js
  src/sections/overview/overview-sales.js
Labels: documentation

#69 🔧 Fixed building with npm run lint-fix
  package.json
  src/contexts/auth-context.js
  src/guards/auth-guard.js
  src/layouts/dashboard/side-nav.js
  src/pages/admin/func/changesubpass.js
  src/pages/admin/func/newsubuser.js
  src/pages/auth/login.js
  src/pages/index.js
  src/pages/readBorreproveRapport.js
  src/pages/readSkrapRapport.js
Labels: bug

#71 🔒 SSL traffic: HTTP -> HTTPS
  src/config/apiConnection.js
Labels: small fix
